"""initial schema

Revision ID: 05981b87a213
Revises: 
Create Date: 2026-08-16 13:09:19.142774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '05981b87a213'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.create_index('ix_import_batch_tenant', ['tenant_id'], unique=False)

    op.create_table('extraction_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.create_index('ix_extraction_job_batch', ['batch_id'], unique=False)

    op.create_table('financial_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gross_amount', app.db.Money(precision=18, scale=2), nullable=True),
    sa.Column('fee_amount', app.db.Money(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', app.db.Money(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', app.db.Money(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('counterparty_name', sa.String(length=300), nullable=True),
    sa.Column('counterparty_account', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=8), nullable=False),
    sa.Column('source_document_name', sa.String(length=300), nullable=False),
    sa.Column('extraction_confidence', app.db.Money(precision=18, scale=2), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('CSV', 'PDF')", name='ck_financial_record_source_type'),
    sa.CheckConstraint("status IN ('NEEDS_REVIEW', 'VALID', 'VALIDATED')", name='ck_financial_record_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.create_index('ix_financial_record_batch_status', ['batch_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_record_batch_status')

    op.drop_table('financial_record')
    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.drop_index('ix_extraction_job_batch')

    op.drop_table('extraction_job')
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batch_tenant')

    op.drop_table('import_batch')
    op.drop_table('tenant')
    # ### end Alembic commands ###
