"""widen extraction job columns

Revision ID: 1653257e517f
Revises: f05516c02a52
Create Date: 2026-08-16 14:25:21.009483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '1653257e517f'
down_revision: Union[str, Sequence[str], None] = 'f05516c02a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.alter_column('document_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('document_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
