"""stored source documents

Revision ID: 1d2b26a0ef3c
Revises: 209694038014
Create Date: 2026-08-16 20:48:06.610016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '1d2b26a0ef3c'
down_revision: Union[str, Sequence[str], None] = '209694038014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("media_type IN ('application/pdf', 'text/csv')", name='ck_source_document_media_type'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_document', schema=None) as batch_op:
        batch_op.create_index('ix_source_document_batch', ['batch_id'], unique=False)
        batch_op.create_index('ix_source_document_hash', ['batch_id', 'content_sha256'], unique=False)

    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_document_id', sa.String(length=36), nullable=True))
        # Named explicitly: batch mode rebuilds the table and refuses to carry
        # a constraint it cannot name.
        batch_op.create_foreign_key(
            'fk_extraction_job_source_document_id',
            'source_document', ['source_document_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_document_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_financial_record_source_document_id',
            'source_document', ['source_document_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_document_id')

    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_document_id')

    with op.batch_alter_table('source_document', schema=None) as batch_op:
        batch_op.drop_index('ix_source_document_hash')
        batch_op.drop_index('ix_source_document_batch')

    op.drop_table('source_document')
    # ### end Alembic commands ###
