"""user display name

Revision ID: 209694038014
Revises: f113e6696c18
Create Date: 2026-08-16 18:48:07.874016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '209694038014'
down_revision: Union[str, Sequence[str], None] = 'f113e6696c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable, backfilled, then tightened -- a server_default would give
    # every existing account the same name.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.Text(), nullable=True))

    # Existing accounts predate the field. The local part of the address is the
    # least surprising stand-in, and the person can change it later.
    #
    # SPLIT_PART rather than SUBSTR/INSTR: INSTR is a SQLite function and this
    # statement made `alembic upgrade head` fail outright on PostgreSQL. The
    # migration had never been executable on the target engine, so it is fixed
    # here rather than papered over by a later revision -- no later migration
    # can repair one that blocks an empty database from reaching head.
    op.execute(
        """
        UPDATE "user"
        SET name = SPLIT_PART(email, '@', 1)
        WHERE name IS NULL
        """
    )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.Text(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
