"""widen user supplied columns

Revision ID: f05516c02a52
Revises: f4b604ca5ca6
Create Date: 2026-08-16 14:16:06.927606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f05516c02a52'
down_revision: Union[str, Sequence[str], None] = 'f4b604ca5ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('counterparty_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('counterparty_account',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('source_document_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.alter_column('source_document_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('invoice_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('counterparty_account',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('counterparty_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
