"""users and refresh tokens

BREAKING FOR EXISTING DATA, and there is no automatic fix.

Before this revision the application had no accounts: every batch belonged to a
default tenant created on demand. Afterwards a tenant is only reachable through
a user, and no user exists for that default tenant -- so any data imported
before this migration becomes invisible.

It cannot be repaired here. Attaching a user would mean inventing a password and
committing it to migration history, which is worse than the problem. The
schema change itself is safe; the data is simply orphaned.

 reports orphaned tenants so an operator knows what
happened, and the README documents the manual step. A fresh installation is
unaffected.

Revision ID: f113e6696c18
Revises: 1653257e517f
Create Date: 2026-08-16 16:28:40.579790

"""
from typing import Sequence, Union

import os

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f113e6696c18'
down_revision: Union[str, Sequence[str], None] = '1653257e517f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ESCAPE_HATCH = "ALLOW_ORPHANED_DATA"


def _refuse_if_data_would_be_orphaned() -> None:
    """Stop rather than silently disconnect existing batches from any account."""
    if os.environ.get(ESCAPE_HATCH) == "1":
        return

    connection = op.get_bind()
    inspector = sa.inspect(connection)
    if "import_batch" not in inspector.get_table_names():
        return

    batches = connection.execute(sa.text("SELECT COUNT(*) FROM import_batch")).scalar() or 0
    if batches == 0:
        return

    raise RuntimeError(
        f"This database holds {batches} batch(es) created before accounts existed. "
        "They belong to a workspace with no user, so after this migration no one "
        "could sign in and reach them.\n\n"
        "Either start from an empty database, or re-import the data into a "
        f"registered account afterwards and set {ESCAPE_HATCH}=1 to proceed."
    )


def upgrade() -> None:
    """Upgrade schema."""
    _refuse_if_data_would_be_orphaned()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_tenant', ['tenant_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_token_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_token_user')

    op.drop_table('refresh_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_tenant')

    op.drop_table('user')
    # ### end Alembic commands ###
