"""import sequence and job status constraint

Revision ID: f4b604ca5ca6
Revises: 05981b87a213
Create Date: 2026-08-16 13:56:19.607754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (app.db.Money) are rendered fully qualified by
# autogenerate, so the module must be importable from every migration.
import app.db  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f4b604ca5ca6'
down_revision: Union[str, Sequence[str], None] = '05981b87a213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("extraction_job", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_extraction_job_status",
            "status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')",
        )

    # Added nullable first so that a table which already holds rows survives the
    # ALTER. A server_default would be simpler but wrong: every existing row
    # would land on sequence 0, so no record would have a predecessor, and the
    # "first occurrence wins" duplicate policy would silently stop working on
    # any pre-existing data.
    with op.batch_alter_table("financial_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_sequence", sa.Integer(), nullable=True))

    # Backfill an arrival order per batch: for each row, count how many rows of
    # the same batch came before it. created_at is the natural order and id
    # breaks ties deterministically.
    #
    # Written with a correlated subquery rather than a window function so the
    # statement runs identically on SQLite and PostgreSQL.
    op.execute(
        """
        UPDATE financial_record
        SET import_sequence = (
            SELECT COUNT(*)
            FROM financial_record AS earlier
            WHERE earlier.batch_id = financial_record.batch_id
              AND (
                    earlier.created_at < financial_record.created_at
                 OR (earlier.created_at = financial_record.created_at
                     AND earlier.id < financial_record.id)
              )
        )
        """
    )

    # Now required, and deliberately WITHOUT a server default: the application
    # must always set the value explicitly. A default would quietly assign 0 to
    # a code path that forgot to allocate a sequence.
    with op.batch_alter_table("financial_record", schema=None) as batch_op:
        batch_op.alter_column("import_sequence", existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(
            "ix_financial_record_batch_sequence", ["batch_id", "import_sequence"], unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_record', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_record_batch_sequence')
        batch_op.drop_column('import_sequence')

    with op.batch_alter_table('extraction_job', schema=None) as batch_op:
        batch_op.drop_constraint('ck_extraction_job_status', type_='check')

    # ### end Alembic commands ###
